# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine

WORKDIR /app

# Copy package and tsconfig files
COPY package.json tsconfig.json ./

# Install dependencies without running any lifecycle scripts
RUN npm install --ignore-scripts

# Copy the rest of the source code
COPY . .

# Build the project
RUN npm run build

# Expose any required ports if needed (optional, not specific in MCP)

# Command to run the MCP server
CMD ["node", "build/index.js"]
